name: test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/checkout@v2
        with:
          python-version: '3.9'
      - name: Test
        run: |
          python test.py
